#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f order_book.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace order_book.sv --exe order_book_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vorder_book.mk Vorder_book

# run executable simulation file
obj_dir/Vorder_book
