#!/bin/sh

# Check if a command line argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <module_name>"
  exit 1
fi

MODULE_NAME=$1

# cleanup
rm -rf obj_dir
rm -f ${MODULE_NAME}.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ../rtl/${MODULE_NAME}.sv --exe ${MODULE_NAME}_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f V${MODULE_NAME}.mk V${MODULE_NAME}

# run executable simulation file
obj_dir/V${MODULE_NAME}
